package com.Employee.DataEmployee.model;
// Generated Nov 26, 2019 9:44:58 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Kemampuan generated by hbm2java
 */
@Entity
@Table(name = "kemampuan", schema = "public")
public class Kemampuan implements java.io.Serializable {

	private Long idKemampuan;
	private KategoriKemampuan kategoriKemampuan;
	private String namaKemampuan;
	private Set<ListKemampuan> listKemampuans = new HashSet<ListKemampuan>(0);

	public Kemampuan() {
	}

	public Kemampuan(Long idKemampuan, String namaKemampuan) {
		this.idKemampuan = idKemampuan;
		this.namaKemampuan = namaKemampuan;
	}

	public Kemampuan(Long idKemampuan, KategoriKemampuan kategoriKemampuan, String namaKemampuan,
			Set<ListKemampuan> listKemampuans) {
		this.idKemampuan = idKemampuan;
		this.kategoriKemampuan = kategoriKemampuan;
		this.namaKemampuan = namaKemampuan;
		this.listKemampuans = listKemampuans;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "kemampuan_id_seq")
	@SequenceGenerator(name="kemampuan_id_seq", sequenceName="kemampuan_id_seq", schema = "public", allocationSize = 1)
	@Column(name = "`ID_KEMAMPUAN`", unique = true, nullable = false)
	public Long getIdKemampuan() {
		return this.idKemampuan;
	}

	public void setIdKemampuan(Long idKemampuan) {
		this.idKemampuan = idKemampuan;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn(name = "`ID_KATEGORI`")
	public KategoriKemampuan getKategoriKemampuan() {
		return this.kategoriKemampuan;
	}

	public void setKategoriKemampuan(KategoriKemampuan kategoriKemampuan) {
		this.kategoriKemampuan = kategoriKemampuan;
	}

	@Column(name = "`NAMA_KEMAMPUAN`", nullable = false, length = 128)
	public String getNamaKemampuan() {
		return this.namaKemampuan;
	}

	public void setNamaKemampuan(String namaKemampuan) {
		this.namaKemampuan = namaKemampuan;
	}

	@OneToMany (fetch = FetchType.LAZY, mappedBy = "kemampuan")
	public Set<ListKemampuan> getListKemampuans() {
		return this.listKemampuans;
	}

	public void setListKemampuans(Set<ListKemampuan> listKemampuans) {
		this.listKemampuans = listKemampuans;
	}

}
