package com.Employee.DataEmployee.model;
// Generated Nov 26, 2019 9:44:58 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PresentaseGaji generated by hbm2java
 */
@Entity
@Table(name = "presentase_gaji", schema = "public")
public class PresentaseGaji implements java.io.Serializable {

	private Long idPresentaseGaji;
	private Posisi posisi;
	private Long idTingkatan;
	private BigDecimal besaranGaji;
	private Integer masaKerja;

	public PresentaseGaji() {
	}

	public PresentaseGaji(Long idPresentaseGaji, BigDecimal besaranGaji) {
		this.idPresentaseGaji = idPresentaseGaji;
		this.besaranGaji = besaranGaji;
	}

	public PresentaseGaji(Long idPresentaseGaji, Posisi posisi, Long idTingkatan, BigDecimal besaranGaji,
			Integer masaKerja) {
		this.idPresentaseGaji = idPresentaseGaji;
		this.posisi = posisi;
		this.idTingkatan = idTingkatan;
		this.besaranGaji = besaranGaji;
		this.masaKerja = masaKerja;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "presentase_gaji_id_seq")
	@SequenceGenerator(name="presentase_gaji_id_seq", sequenceName="presentase_gaji_id_seq", schema = "public", allocationSize = 1)
	@Column(name = "`ID_PRESENTASE_GAJI`", unique = true, nullable = false)
	public Long getIdPresentaseGaji() {
		return this.idPresentaseGaji;
	}

	public void setIdPresentaseGaji(Long idPresentaseGaji) {
		this.idPresentaseGaji = idPresentaseGaji;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn(name = "`ID_POSISI`")
	public Posisi getPosisi() {
		return this.posisi;
	}

	public void setPosisi(Posisi posisi) {
		this.posisi = posisi;
	}

	@Column(name = "`ID_TINGKATAN`")
	public Long getIdTingkatan() {
		return this.idTingkatan;
	}

	public void setIdTingkatan(Long idTingkatan) {
		this.idTingkatan = idTingkatan;
	}

	@Column(name = "`BESARAN_GAJI`", nullable = false, precision = 16, scale = 4)
	public BigDecimal getBesaranGaji() {
		return this.besaranGaji;
	}

	public void setBesaranGaji(BigDecimal besaranGaji) {
		this.besaranGaji = besaranGaji;
	}

	@Column(name = "`MASA_KERJA`")
	public Integer getMasaKerja() {
		return this.masaKerja;
	}

	public void setMasaKerja(Integer masaKerja) {
		this.masaKerja = masaKerja;
	}

}
