package com.Employee.DataEmployee.model;
// Generated Nov 26, 2019 9:44:58 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TunjanganPegawai generated by hbm2java
 */
@Entity
@Table(name = "tunjangan_pegawai", schema = "public")
public class TunjanganPegawai implements java.io.Serializable {

	private Long idTunjanganPegawai;
	private Posisi posisi;
	private Tingkatan tingkatan;
	private BigDecimal besaranTujnaganPegawai;

	public TunjanganPegawai() {
	}

	public TunjanganPegawai(Long idTunjanganPegawai, BigDecimal besaranTujnaganPegawai) {
		this.idTunjanganPegawai = idTunjanganPegawai;
		this.besaranTujnaganPegawai = besaranTujnaganPegawai;
	}

	public TunjanganPegawai(Long idTunjanganPegawai, Posisi posisi, Tingkatan tingkatan,
			BigDecimal besaranTujnaganPegawai) {
		this.idTunjanganPegawai = idTunjanganPegawai;
		this.posisi = posisi;
		this.tingkatan = tingkatan;
		this.besaranTujnaganPegawai = besaranTujnaganPegawai;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "tunjangan_pegawai_id_seq")
	@SequenceGenerator(name="tunjangan_pegawai_id_seq", sequenceName="tunjangan_pegawai_id_seq", schema = "public", allocationSize = 1)
	@Column(name = "`ID_TUNJANGAN_PEGAWAI`", unique = true, nullable = false)
	public Long getIdTunjanganPegawai() {
		return this.idTunjanganPegawai;
	}

	public void setIdTunjanganPegawai(Long idTunjanganPegawai) {
		this.idTunjanganPegawai = idTunjanganPegawai;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn(name = "`ID_POSISI`")
	public Posisi getPosisi() {
		return this.posisi;
	}

	public void setPosisi(Posisi posisi) {
		this.posisi = posisi;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn(name = "`ID_TINGKATAN`")
	public Tingkatan getTingkatan() {
		return this.tingkatan;
	}

	public void setTingkatan(Tingkatan tingkatan) {
		this.tingkatan = tingkatan;
	}

	@Column(name = "`BESARAN_TUJNAGAN_PEGAWAI`", nullable = false, precision = 16, scale = 4)
	public BigDecimal getBesaranTujnaganPegawai() {
		return this.besaranTujnaganPegawai;
	}

	public void setBesaranTujnaganPegawai(BigDecimal besaranTujnaganPegawai) {
		this.besaranTujnaganPegawai = besaranTujnaganPegawai;
	}

}
